### ISSUE TITLE
Working 1.16.5?

### ISSUE THREAD

**Issue by GamingCarmelo** [DrkMatr1984/Piggyback#10]
Is this plugin compatible with 1.16.5? or atleast working with 1.16.5?

**Comment by Teddro** [comment]
We use Piggyback on our server and it works. We are 1.16.5. Praying it works with the new update. Otherwise people are gonna cry. lol!

**Comment by DrkMatr1984** [comment]
I will try to make time for a major update soon guys. Truth is, I don't even really play MC anymore. But its hard abandoning something you worked so hard on at one point, so I'll probably get to this sooner or later :)
