### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by mercurialmusic** [DrkMatr1984/Piggyback#11]
Hey man! Hope you're well. Not sure if you're still working on this one at all but it's still going great in 1.18.1! Just a bit of error spam every time someone picks something up:

https://gist.github.com/mercurialmusic/f9f7cee904278afbe6f5260b9e6b50ce

Thanks and take care!

**Comment by DrkMatr1984** [comment]
Not really, but I'll update it for 1.18! There's still unfinished code for a feature I never finished, included. I'll push a quick update for 1.18 and maybe in the upcoming months push a proper update.

**Comment by mercurialmusic** [comment]
Sweet, thanks!

**Comment by DrkMatr1984** [comment]
Hey mercurialmusic,
     I believe I may have fixed this a commit ago, but never pushed an update. Can u check [this build](https://github.com/DrkMatr1984/Piggyback/releases/tag/untagged-8209a29a4a940eaea3eb) and see if it fixes spam?

**Comment by mercurialmusic** [comment]
That link seems to be broken, or perhaps private? The last release I see here is from 2016. You had mentioned the update a couple years ago maybe when I reached out on Spigot, but I wasn't able to find it then either.

**Comment by DrkMatr1984** [comment]
🤦‍♂️ I forgot to publish it and it was still a draft. [Here ya go](https://github.com/DrkMatr1984/Piggyback/releases/tag/2.1)

**Comment by DrkMatr1984** [comment]
Actually I almost have a full build done. Should be up on spigot by morning. 👍

**Comment by DrkMatr1984** [comment]
https://www.spigotmc.org/resources/piggyback-more-than-just-a-stacker.14130/

**Comment by mercurialmusic** [comment]
Thanks dude! Seriously, this plugin is amazing -- we have a lot of fun with it.

**Comment by DrkMatr1984** [comment]
No problem! It was not in as much sorry shape as I had thought lol.
