### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by mercurialmusic** [DrkMatr1984/Piggyback#4]
Still getting this error with PiggyBack 2.0 every time someone picks up a mob: https://pastebin.com/TpMw3HMB

**Comment by DrkMatr1984** [comment]
Really weird, I never get this error on my setup. Can you send me a copy of your entire log zipped up? Thanks!

**Comment by mercurialmusic** [comment]
That's the only relevant bit in the log -- startup is normal, no errors, just throws those when the plugin is actually used -- from the in-game perspective it seems to work, but it spams those every time. I don't really fancy putting the entire log on here, so if you can direct me to what you're looking for I can provide that.

**Comment by DrkMatr1984** [comment]
How bout just send me your language file from piggyback and let me know if you're running paperspigot,  spigot,  or craftbukkit.

**Comment by mercurialmusic** [comment]
Sure thing. Running the latest build of Spigot. Github won't let me attach the .yml, so here's the pastebin of it: https://pastebin.com/WvS19fyf

**Comment by DrkMatr1984** [comment]
Sorry I didn't notice this. I'll give it a go, but it could be the double ' located in this
`notAPlayer: "&cYou're not a player! You can''t toggle being picked up!&r"`
at the can''t

**Comment by DrkMatr1984** [comment]
Ahhhh I think I see the problem xD
Your language.yml is missing a few values added in more recent versions of the plugin. 
You could rename your current one and let a new one generate, or use this one (Github will let you attach zips, this is just the default language.yml in a zip file)
[language.zip](https://github.com/DrkMatr1984/Piggyback/files/1845017/language.zip)

**Comment by DrkMatr1984** [comment]
Or check it out here

https://github.com/DrkMatr1984/Piggyback/blob/master/src/main/resources/language.yml

And add the changes manually to your language file.

**Comment by DrkMatr1984** [comment]
Did it work? If so, let me know so I can close the issue. :+1:

**Comment by mercurialmusic** [comment]
Sorry, didn't realize how long it's been. Yes, I think we're good. Thanks for your help!
