### ISSUE TITLE
Piggyback for 1.14 ?

### ISSUE THREAD

**Issue by Teddro** [DrkMatr1984/Piggyback#6]
Will there be an update for Piggyback to the 1.14 version? I already have the hoards of fans worried about this one. I sure hope so. It's a favorite.

**Comment by DrkMatr1984** [comment]
Yeah! I'll be updating it :)

**Comment by Teddro** [comment]
Sweet! So excited :) Thank you

**Comment by DrkMatr1984** [comment]
Sorry so late! I am working on this today! :)

**Comment by Teddro** [comment]
Thank you so much! I know you’re busy, too. :)

**Comment by DrkMatr1984** [comment]
No problem :) The version I have compiled now should work with 1.14. I am adding a few more features and closing some of these support tickets while I am at it, but if you need something that will get you going for now I can give you a jar. Email me DrkMatr1984@gmail.com if you need one
